<a name="loesung07"></a>Solutions exercise 08
===

In [1]:
# 1.a
# import random and numpy
# note: call numpy using 'np'
import random
import numpy as np

# create a list of 100 random integers between 0 and 100
numbers = [random.randint(0,101) for i in range(100)]
# convert the list to an array
numbers = np.asarray(numbers)
# "reshape" the 1-d array to a 2-d 10x10 matrix
numbers = numbers.reshape((10,10))
print(numbers)

[[27 10 18 89 41 42 41 14 52 34]
 [67 43 18 47 90 35 46  8 95 99]
 [60 12 31 25 76 73 26 56 45 47]
 [62 93 64 15 26 60 97 49 11 99]
 [76  7 28  7 78  6 14  9  6 55]
 [34 38 42 40 59 92 47 93 45 38]
 [93 41  0 60 74 27 61 44 48 33]
 [96 71 10 76 28 73 88 43 81 80]
 [97 36 20 56 18 32  7 12 81 41]
 [34 52 70 80  9 20 57  4 15  2]]


In [ ]:
# 1.b
np.savetxt('random-numbers.txt', numbers)

In [ ]:
# 1.c
# Documentation to numpy.random.randint:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html

numbers = np.random.randint(0, 101, (10,10))
print(numbers)

In [ ]:
# 1.d
print('upper left:')
upper_left = numbers[:5, :5]
print(upper_left)
print('upper right:')
upper_right = numbers[:5, 5:]
print(upper_right)
print('lower left:')
down_left = numbers [5:, :5]
print(down_left)
print('lower right:')
down_right = numbers[5:, 5:]
print(down_right)

In [ ]:
# 1.e
matrix_product = np.dot(upper_left, upper_right)
print(matrix_product)

# the same for the other multiplications

In [ ]:
# 1.f
# create a new matrix
# take a look in the matrix upper_right:
# if upper_right > 50, take an element from lower_left
# if upper_right < 50, take an element from lower_right
new_matrix = np.where(upper_right > 50, down_left, down_right)
print(new_matrix)